[xorg-server]
# source = "regex"
# regex = "xorg-server-([\\d.]+)\\."
# url = "https://gitlab.freedesktop.org/xorg/xserver/-/tags"
# include_regex = "^\\d+\\.\\d+\\.\\d+$"
# exclude_regex = "^\\d+\\.\\d+\\.99$"

source="archpkg"
