# https://download.nvidia.com/XFree86/Linux-x86_64/595.58.03/README/powermanagement.html
# Enable Suspend Notifiers for faster and more modern suspend
# when the open kernel modules are in use
options nvidia NVreg_UseKernelSuspendNotifiers=1
#
# The destination should not be using tmpfs, so we prefer
# /var/tmp instead of /tmp
options nvidia NVreg_TemporaryFilePath=/var/tmp
#
# To unlock the full functionality of the interface with the proprietary driver, 
# the NVIDIA Linux kernel module nvidia.ko needs to be loaded with
options nvidia NVreg_PreserveVideoMemoryAllocations=1
