post_upgrade() {
  # Show warning for users of older packages
  if (( $(vercmp $2 '24.004.60-3.1') < 0 )); then
    echo "WARNING: The 'plymouth-encrypt' and 'sd-plymouth' hooks are depreciated. You should replace them with 'encrypt' and 'plymouth' hooks in your 'mkinitcpio.conf'. The 'lxdm-plymouth.service', 'lightdm-plymouth.service' and 'sddm-plymouth.service' systemd service files are no longer recommended. You should enable 'lxdm.service', 'lightdm.service' or 'sddm.service' instead."
  fi
}

